version: '3'
services:
  challenge:
    container_name: BufferOverFlow
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - 12444:10001
    read_only: true
    cap_drop:
      - all
              
    restart: on-failure
